imx-gpu-viv: set RPROVIDES:libegl-imx explicitly
Issue: LIN1025-3086

If "RPROVIDES:xxx = yyy" is set by calling "d.appendVar" in a __anonymous
python function, there will be no expansion "RPROVIDES:lib32-xxx =
lib32-yyy" since the __anonymous python function runs in a late stage.

Since lib32-xwayland requires lib32-libegl, set RPROVIDES:libegl-imx
explicitly in recipe instead of in the __anonymous python function.

This patch fixes the following error:

    ERROR: Nothing RPROVIDES 'lib32-libegl' (but virtual:multilib:lib32:/layers/oe-core/meta/recipes-graphics/xwayland/xwayland_24.1.6.bb RDEPENDS on or otherwise requires it)

(LOCAL REV: NOT UPSTREAM) - Will send to meta-freescale

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>